"""Initial migration

Revision ID: 157280e4492c
Revises: 
Create Date: 2026-01-30 09:06:06.025656

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '157280e4492c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=True),
    sa.Column('last_name', sa.String(length=100), nullable=True),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('last_login', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)

    op.create_table('artifacts',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('sequence_number', sa.String(length=50), nullable=False),
    sa.Column('accession_number', sa.String(length=100), nullable=True),
    sa.Column('other_accession_number', sa.String(length=255), nullable=True),
    sa.Column('on_display', sa.Boolean(), nullable=True),
    sa.Column('acquisition_details', sa.Text(), nullable=True),
    sa.Column('object_type', sa.String(length=255), nullable=True),
    sa.Column('material', sa.String(length=100), nullable=True),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.Column('size_dimensions', sa.Text(), nullable=True),
    sa.Column('weight', sa.String(length=100), nullable=True),
    sa.Column('technique', sa.String(length=255), nullable=True),
    sa.Column('description_catalogue', sa.Text(), nullable=True),
    sa.Column('description_observation', sa.Text(), nullable=True),
    sa.Column('inscription', sa.Text(), nullable=True),
    sa.Column('findspot', sa.String(length=255), nullable=True),
    sa.Column('production_place', sa.String(length=255), nullable=True),
    sa.Column('chronology', sa.String(length=255), nullable=True),
    sa.Column('bibliography', sa.Text(), nullable=True),
    sa.Column('photo_number', sa.String(length=255), nullable=True),
    sa.Column('created_by', sa.String(length=36), nullable=True),
    sa.Column('updated_by', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('artifacts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_artifacts_accession_number'), ['accession_number'], unique=False)
        batch_op.create_index(batch_op.f('ix_artifacts_material'), ['material'], unique=False)
        batch_op.create_index(batch_op.f('ix_artifacts_object_type'), ['object_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_artifacts_sequence_number'), ['sequence_number'], unique=True)

    op.create_table('media',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('artifact_id', sa.String(length=36), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('original_filename', sa.String(length=255), nullable=False),
    sa.Column('mime_type', sa.String(length=100), nullable=True),
    sa.Column('file_size', sa.Integer(), nullable=True),
    sa.Column('width', sa.Integer(), nullable=True),
    sa.Column('height', sa.Integer(), nullable=True),
    sa.Column('dropbox_path', sa.String(length=500), nullable=False),
    sa.Column('thumbnail_path', sa.String(length=500), nullable=True),
    sa.Column('is_primary', sa.Boolean(), nullable=True),
    sa.Column('caption', sa.Text(), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=True),
    sa.Column('uploaded_by', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['artifact_id'], ['artifacts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['uploaded_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('media', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_media_artifact_id'), ['artifact_id'], unique=False)

    op.create_table('submissions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('researcher_name', sa.String(length=255), nullable=False),
    sa.Column('researcher_institution', sa.String(length=255), nullable=True),
    sa.Column('researcher_address', sa.Text(), nullable=True),
    sa.Column('researcher_email', sa.String(length=255), nullable=False),
    sa.Column('storage_location', sa.String(length=255), nullable=True),
    sa.Column('object_name', sa.String(length=255), nullable=True),
    sa.Column('dimensions', sa.Text(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('artifact_id', sa.String(length=36), nullable=True),
    sa.Column('reviewed_by', sa.String(length=36), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(), nullable=True),
    sa.Column('review_notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['artifact_id'], ['artifacts.id'], ),
    sa.ForeignKeyConstraint(['reviewed_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('annotations',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('media_id', sa.String(length=36), nullable=False),
    sa.Column('annotation_type', sa.String(length=20), nullable=False),
    sa.Column('geometry', sa.JSON(), nullable=False),
    sa.Column('stroke_color', sa.String(length=20), nullable=True),
    sa.Column('stroke_width', sa.Integer(), nullable=True),
    sa.Column('stroke_style', sa.String(length=20), nullable=True),
    sa.Column('fill_color', sa.String(length=20), nullable=True),
    sa.Column('fill_opacity', sa.Float(), nullable=True),
    sa.Column('label', sa.String(length=255), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('extra_data', sa.JSON(), nullable=True),
    sa.Column('created_by', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['media_id'], ['media.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('annotations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_annotations_media_id'), ['media_id'], unique=False)

    op.create_table('submission_images',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('submission_id', sa.String(length=36), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('original_filename', sa.String(length=255), nullable=True),
    sa.Column('dropbox_path', sa.String(length=500), nullable=False),
    sa.Column('thumbnail_path', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['submission_id'], ['submissions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('submission_images', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_submission_images_submission_id'), ['submission_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('submission_images', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_submission_images_submission_id'))

    op.drop_table('submission_images')
    with op.batch_alter_table('annotations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_annotations_media_id'))

    op.drop_table('annotations')
    op.drop_table('submissions')
    with op.batch_alter_table('media', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_media_artifact_id'))

    op.drop_table('media')
    with op.batch_alter_table('artifacts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_artifacts_sequence_number'))
        batch_op.drop_index(batch_op.f('ix_artifacts_object_type'))
        batch_op.drop_index(batch_op.f('ix_artifacts_material'))
        batch_op.drop_index(batch_op.f('ix_artifacts_accession_number'))

    op.drop_table('artifacts')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    # ### end Alembic commands ###
