"""Add folder and tags to media

Revision ID: c8c028386cf7
Revises: ec39dca4b4b4
Create Date: 2026-01-31 08:37:05.763514

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c8c028386cf7'
down_revision = 'ec39dca4b4b4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('media', schema=None) as batch_op:
        batch_op.add_column(sa.Column('folder', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('tags', sa.JSON(), nullable=True))
        batch_op.create_index(batch_op.f('ix_media_folder'), ['folder'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('media', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_media_folder'))
        batch_op.drop_column('tags')
        batch_op.drop_column('folder')

    # ### end Alembic commands ###
