"""Add collection field to artifacts

Revision ID: cd8716a6fa42
Revises: 157280e4492c
Create Date: 2026-01-30 15:30:02.203680

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cd8716a6fa42'
down_revision = '157280e4492c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('artifacts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('collection', sa.String(length=50), nullable=False))
        batch_op.create_index(batch_op.f('ix_artifacts_collection'), ['collection'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('artifacts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_artifacts_collection'))
        batch_op.drop_column('collection')

    # ### end Alembic commands ###
