"""Add British Museum URL and external links to artifacts

Revision ID: ec39dca4b4b4
Revises: cd8716a6fa42
Create Date: 2026-01-30 20:19:35.004902

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ec39dca4b4b4'
down_revision = 'cd8716a6fa42'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('artifacts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('british_museum_url', sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column('external_links', sa.JSON(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('artifacts', schema=None) as batch_op:
        batch_op.drop_column('external_links')
        batch_op.drop_column('british_museum_url')

    # ### end Alembic commands ###
